lang: es
quarto-required: ">= 1.6"

project:
  type: book
  output-dir: docs
book:
  title: "Curso Introductorio al Análisis de Algoritmos con Julia"
  author: 
    - name: "Eric S. Téllez"
      url: https://sadit.github.io
      affiliation: INFOTEC Centro de Investigación e Innovación en Tecnologías de la Información y Comunicación    
  chapters:
    - index.qmd
    - cap1-julia.qmd
    - cap2-analisis.qmd
    - cap3-estructuras.qmd
    - cap4-ordenamiento.qmd
    - cap5-busqueda.qmd
    - cap6-intersecciones.qmd
    - refs.qmd
  appendices:
    - galeria-actividades.qmd
  site-url: https://sadit.github.io/ALGO-IR
  repo-url: https://github.com/sadit/ALGO-IR
  downloads: pdf
  page-footer:
    right: |
      [![](https://i.creativecommons.org/l/by-sa/4.0/80x15.png)](http://creativecommons.org/licenses/by-sa/4.0/) <br/> Esta obra está bajo una [Licencia Creative Commons Atribución-CompartirIgual 4.0 Internacional](http://creativecommons.org/licenses/by-sa/4.0/)

bibliography: refs.bib
title-block-banner: true
highlight-style: pygments

engine: julia


format:
  html:
    theme: default
    code-tools: true
    echo: true
  pdf:
    documentclass: scrbook
    echo: true
    toc: true
    colorlinks: true
    papersize: letter

execute:
  freeze: auto
